# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11DkveGIWE8W0B2blSTzC-MpNVCg2MZbg
"""

import streamlit as st
import pandas as pd

st.write("""
#Largest number prediction App""")

st.header('User inputs')

def user_input_features():
  num1 = st.number_input("num1", min_value = 0.0, max_value = 2000000000)
  num2 = st.number_input("num2", min_value = 0.0, max_value = 2000000000)
  num3 = st.number_input("num3", min_value = 0.0, max_value = 2000000000)

  data = {"num1": num1,
        "num2": num2,
        "num3": num3
         }
  features = pd.DataFrame(data, index[0])
  return features

  res = max(num1,num2,num3)

  st.subheader("Result")
  st.write(res)

